# Dockerfile.frontend

# Get the base Image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json before other files
# Utilise Docker cache to save re-installing dependencies if unchanged
COPY package*.json ./

RUN npm install axios react-router-dom



# Copy the rest of the application
COPY . .

# Expose the port 
EXPOSE 3000

CMD [ "npm", "start" ]
