version: '3'
services:
  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CI=true

  node:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app/backend
      - /app/node_modules
    ports:
      - 5000:5000
    depends_on:
      - mysql
      #mysql:
      #  condition: service_healthy
      
  mysql:
      image: mysql:5.7
      #command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydb
      ports:
        - 3306:3306
      volumes:
        - ./mysql-init/:/docker-entrypoint-initdb.d/  # Add this line
      healthcheck:
        test: ["CMD", "mysqladmin", "-u", "root", "-ppassword", "ping", "-h", "localhost"]
        timeout: 5s
        retries: 10
      #volumes:
      #  - ./mysql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
