version: '3'
services:
  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CI=true

  node:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 5000:5000
    depends_on:
      mysql:
        condition: service_healthy
      
  mysql:
      image: mysql:5.7
      user: "1000:1000"
      #command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydb
      ports:
        - 3306:3306
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10
