version: '3.1'
services:
  react:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/usr/src/app/frontend
    ports:
      - 3000:3000
    environment:
      - CI=true

  node:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app/
      - /app/node_modules

    ports:
      - 5001:5001
    depends_on:
      - mysql
      
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306
    volumes:
      - ./db-data/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "-u", "root", "-ppassword", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

volumes:
  db-data:
